services:
  cesizen-database:
    container_name: cesizen_database
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: "0:0"
    environment:
      SA_PASSWORD: "chaisea3Pieds!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      # Optimisations mémoire pour 4GB RAM
      MSSQL_MEMORY_LIMIT_MB: "2048"  # Réserver 2GB pour SQL Server
      MSSQL_TCP_PORT: "1433"
    ports:
      - "1433:1433"
    volumes:
      - cesizen_sqldata:/var/opt/mssql/data
    networks:
      - cesizen-network
    restart: unless-stopped
    # Limites containers optimisées pour 4GB
    deploy:
      resources:
        limits:
          memory: 2.5G
        reservations:
          memory: 1.5G
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P ${DB_PASSWORD} -Q 'SELECT 1' -No"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10S  # Plus de temps pour le démarrage

  cesizen-app:
    container_name: cesizen_app
    image: "ghcr.io/valentinwlt/cesizen:latest"
    depends_on:
      cesizen-database:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=cesizen-database;Database=CESIZenDB;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=true;Connection Timeout=60;"
      # Optimisations ASP.NET Core
      ASPNETCORE_URLS: "http://+:8080"
      DOTNET_GCServer: "1"
      DOTNET_GCConcurrent: "1"
      DOTNET_GCRetainVM: "1"
    ports:
      - "8080:8080"
    networks:
      - cesizen-network
    restart: unless-stopped
    # Limites pour l'application ASP.NET
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M


volumes:
  cesizen_sqldata:
    driver: local

networks:
  cesizen-network:
    driver: bridge
    name: cesizen-network