name: 01-1 - Test Application

on:
  workflow_call

jobs:
  TestDotNet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: |
          dotnet test R2.Tests/R2.Tests.csproj \
            --configuration Release \
            --no-build \
            --verbosity normal \
            --collect:"XPlat Code Coverage" \
            --results-directory ./coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-coverage-report
          path: ./coverage
          retention-days: 3

  TestE2E:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create docker-compose for tests
        run: |
          cat > docker-compose-test.yml << 'EOF'
          services:
            r2-database:
              container_name: r2_database_test
              image: mcr.microsoft.com/mssql/server:2022-latest
              user: "0:0"
              environment:
                SA_PASSWORD: "R2SecurePass123!"
                ACCEPT_EULA: "Y"
                MSSQL_PID: "Express"
              ports:
                - "1434:1433"  # Port différent pour éviter les conflits
              volumes:
                - r2_test_sqldata:/var/opt/mssql/data
              healthcheck:
                test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P R2SecurePass123! -Q 'SELECT 1'"]
                interval: 30s
                timeout: 10s
                retries: 5
              networks:
                - r2-test-network

          volumes:
            r2_test_sqldata:

          networks:
            r2-test-network:
              driver: bridge
          EOF

      - name: Start Database for E2E
        run: |
          docker compose -f docker-compose-test.yml up -d r2-database
          echo "⏳ Waiting for database to be ready..."
          sleep 45

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build and Run App for E2E
        run: |
          # Utiliser une connection string pointant vers le conteneur de test
          export ConnectionStrings__DefaultConnection="Server=localhost,1434;Database=RessourcesRelationnelles;User Id=sa;Password=R2SecurePass123!;TrustServerCertificate=true;"
          export ASPNETCORE_ENVIRONMENT="Testing"
          export ASPNETCORE_HTTP_PORTS="5000"
          
          dotnet build --configuration Release
          # Lancer l'app en arrière-plan
          dotnet run --project R2.UI/R2.UI.csproj --configuration Release --urls "http://localhost:5000" &
          APP_PID=$!
          echo "APP_PID=$APP_PID" >> $GITHUB_ENV
          
          # Attendre que l'app soit prête
          echo "⏳ Waiting for app to start..."
          for i in {1..30}; do
            if curl -s http://localhost:5000/health > /dev/null 2>&1; then
              echo "✅ App is ready!"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "❌ App failed to start in time"
              exit 1
            fi
            sleep 2
          done

      - name: Run E2E Tests
        run: |
          echo "🧪 Running E2E tests..."
                    
          # Test homepage
          echo "Testing homepage..."
          curl -f http://localhost:5000/ || (echo "❌ Homepage test failed" && exit 1)
          
          # Test response time
          echo "Testing response time..."
          RESPONSE_TIME=$(curl -o /dev/null -s -w "%{time_total}" http://localhost:5000/)
          echo "Response time: ${RESPONSE_TIME}s"
          
          # Vérifier que le temps de réponse est acceptable (< 5 secondes pour les tests)
          if (( $(echo "$RESPONSE_TIME > 5.0" | bc -l) )); then
            echo "⚠️ Response time is slow but acceptable for tests: ${RESPONSE_TIME}s"
          fi
          
          echo "✅ All E2E tests passed!"

      - name: Stop Application
        if: always()
        run: |
          if [ ! -z "$APP_PID" ]; then
            echo "Stopping application (PID: $APP_PID)"
            kill $APP_PID 2>/dev/null || true
          fi

      - name: Clean Docker
        if: always()
        run: |
          echo "🧹 Cleaning up Docker resources..."
          docker compose -f docker-compose-test.yml down -v || true
          docker system prune -f || true
          echo "✅ Cleanup completed"