name: 01-2 - Integration SonarQube (Test)

on:
  workflow_call

jobs:
  QualityDotNet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Install SonarCloud scanner
        run: |
          dotnet tool install --global dotnet-sonarscanner

      - name: Restore dependencies
        run: dotnet restore

      - name: Test SonarCloud Connection
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "🔍 Testing SonarCloud connection with correct info..."
          echo "Organization: bloc3-orga"
          echo "Project: bloc3-orga_RessourcesRelationnelles"
          
          # Test simple avec les bonnes informations
          dotnet sonarscanner begin \
            /k:"bloc3-orga_RessourcesRelationnelles" \
            /o:"bloc3-orga" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io"
          
          dotnet build --configuration Release --no-restore
          
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          
          echo "✅ SonarCloud test completed!"