name: 02 - Deploy

on: 
  push:
    branches:
      - main

jobs:
  Security_Check:
    uses: ./.github/workflows/01-3_Security.yaml

  Dockerbuild:
    needs: [Security_Check]
    uses: ./.github/workflows/02-1_Dockerbuild.yaml
    secrets: inherit

  Deploy:
    needs: [Dockerbuild]
    uses: ./.github/workflows/02-2_Deploy.yaml
    secrets: inherit