name: 02 - Deploy

on: 
  push:
    branches:
      - main

jobs:
  Security_Check:
    uses: ./.github/workflows/01-3_Security.yml

  Dockerbuild:
    needs: [Security_Check]
    uses: ./.github/workflows/02-1_Dockerbuild.yml
    secrets: inherit

  Deploy:
    needs: [Dockerbuild]
    uses: ./.github/workflows/02-2_Deploy.yml
    secrets: inherit