name: 02 - Deploy

on: 
  push:
    branches:
      - main

jobs:
  SnykSecurity:
    uses: ./.github/workflows/01-4_SnykSecurity.yml
    with:
      scan_type: 'dependencies' 
    secrets: inherit

  Dockerbuild:
    needs: [SnykSecurity] 
    uses: ./.github/workflows/02-1_Dockerbuild.yml
    secrets: inherit

  Deploy:
    needs: [Dockerbuild]
    uses: ./.github/workflows/02-2_Deploy.yml
    secrets: inherit